package com.example.jordi.project.Constants;

public class Constantes {
    public static final String URL = "https://api.themoviedb.org";
    public static final String CATEGORY = "category";
    public static final String API_KEY = "api_key";
    public static final String LANGUAGE = "language";
    public static final String PAGE = "page";
    public static final String BASE_URL_IMAGE = "http://image.tmdb.org/t/p/w300";
    public static final String PACKAGE = "com.example.jordi.project";
    public static final String SESION_GUARDADA ="sesion_Guardada";
    public static final String PREFERECE_USER_LOGIN = "user_login";




    //SERIES DESCRIPCIONES
    public static final String DESCRIPCIO_CASAPAPEL = "Serie que narra un atraco perfecto, no a un banco, sino nada menos que a la Fábrica Nacional de Moneda y Timbre. Todo comienza cuando un engimático personaje, el profesor (Álvaro Morte) planea algo grande, único: llevar a cabo el mayor atraco de la historia. Para ello recluta una banda de siete personas que reúnen un único requisito: ninguno tiene nada que perder. “¿Cómo te suenan 2.400 millones de euros?”, es lo que le plantea a Tokio (Úrsula Corberó), una joven experta en atracos que se encuentra en busca y captura por la policía. Ella se unirá al grupo reclutado por El Profesor y conformado por: Berlín (Pedro Alonso), el cabecilla; Moscú (Paco Tous), el experto en perforaciones; Río (Miguel Herrán), el informático; Nairobi (Alba Flores), la falsificadora; Denver (Jaime Lorente), hijo de Moscú; Helsinki (Darko Peric) y Oslo (Roberto García Ruiz), la fuerza bruta. Cinco meses de reclusión memorizando cada paso, cada detalle, cada probabilidad… y por fin, once días de encierro en la Fábrica Nacional de Moneda y Timbre, rodeados de los cuerpos de élite de la policía y con 67 rehenes en su poder para saber si saldrán vencedores de su apuesta suicida. Será todo o nada.";
    public static final String DESCRIPCIO_BLACKMIRROR = "Black Mirror es una serie de televisión británica creada por Charlie Brooker que muestra el lado oscuro de la vida y la tecnología. La serie es producida por Zeppotron para Endemol. En cuanto al contenido del programa y la estructura, Brooker ha señalado que \"cada episodio tiene un tono diferente, un entorno diferente, incluso una realidad diferente, pero todos son acerca de la forma en que vivimos ahora - y la forma en que podríamos estar viviendo en 10 minutos si somos torpes";
    public static final String DESCRIPCIO_TWD = "Tras un apocalipsis zombie, un grupo de supervivientes, dirigidos por el policía Rick Grimes, recorre los Estados Unidos para ponerse a salvo. Aunque el leit motiv de la serie sea el apocalipsis zombie, la narración se centra más en las relaciones entre los personajes, su evolución y comportamiento en las situaciones críticas. Entre ellos destaca el ayudante del sheriff de un pueblo de Georgia que entró en coma durante la catástrofe.";
    public static final String DESCRIPCIO_WESTWORLD = "Westworld es una ambiciosa serie de ficción repleta de imaginación que eleva el concepto de las aventuras y las emociones fuertes a un nuevo nivel de peligrosidad. En el futurista parque temático conocido como Westworld, un grupo de androides-servidores se desvían de las secuencias programadas meticulosamente por los informáticos y adoptan un comportamiento anormal. Con un reparto espectacular encabezado por Anthony Hopkins, Ed Harris, Evan Rachel Wood, James Marsden, Thandie Newton y Jeffrey Wright, Westworld está basada en la película de 1973 escrita y dirigida por Michael Crichton (Parque jurásico), y ha sido creada para la televisión por los productores ejecutivos Jonathan Nolan (Interstellar, El caballero oscuro) y Lisa Joy (Criando malvas, Último aviso).";
    public static final String DESCRIPCIO_ALTEREDCARBON = "‘Altered Carbon’ es ciencia ficción cyberpunk y está ambientada en un S. XXV en el que la mente ha sido digitalizada. Takeshi Kovacs lleva en prisión 500 años y es descargado en el futuro para resolver un asesinato en un mundo donde la tecnología ha convertido la muerte en algo casi obsoleto. Así, podrá salir de prisión y tener una segunda oportunidad.";
    public static final String DESCRIPCIO_RICKMORTY = "Rick es un abuelo y un desequilibrado mental alcohólico que ha vuelto a contactar con su familia. También es un genio científico, que pasa la mayoría del tiempo llevando a su joven nieto Morty (y otros miembros de la familia posteriormente) en peligrosas y extravagantes aventuras a través de nuestro cosmos y universos paralelos. Sumando a ello la inestabilidad de la familia de Morty, estas aventuras causan angustia a Morty, tanto en la escuela como en casa.";
    public static final String DESCRIPCIO_ORANGEBLACK = "Piper Chapman (Taylor Schiling), una mujer de Connecticut con una vida estable y un alto cargo ejecutivo, es detenida a raíz de un delito de drogas que cometió hace una década: en aquellos días llevó un maletín con dinero de la droga para Alex Vause (Laura Prepon), una traficante y antigua amante de Piper. Tras el juicio, es enviada a prisión de mujeres en Litchfield, Nueva York. Basada en las vivencias reales de Kerman, cuya experiencia entre rejas le sirvió para escribir el best-seller autobiográfico Orange Is The New Black: My Year In A Womens Prison. A medio camino entre el drama y la comedia, una aclamada serie -fue una de las que mejor críticas obtuvo en su primera temporada en el 2013- que aborda temas relacionados con la cárcel como el sistema penitenciario norteamericano, el lesbianismo, la represión sexual, el abuso de poder o la corrupción policial.";
    public static final String DESCRIPCIO_LUKECAGE = "Como consecuencia de un experimento fallido, Luke Cage (Mike Colter) ha desarrollado una piel indestructible y una fuerza sobrehumana. Ahora es un fugitivo que intenta rehacer su vida en el barrio neoyorquino de Harlem. Pronto se verá obligado a salir de la sombra, luchar por su ciudad y afrontar un pasado que quería enterrar.";
    public static final String DESCRIPCIO_BREAKINGBAD = "Tras cumplir 50 años, Walter White (Bryan Cranston), un profesor de química de un instituto de Albuquerque, Nuevo México, se entera de que tiene un cáncer de pulmón incurable. Casado con Skyler (Anna Gunn) y con un hijo discapacitado (RJ Mitte), la brutal noticia lo impulsa a dar un drástico cambio a su vida: decide, con la ayuda de un antiguo alumno (Aaron Paul), fabricar anfetaminas y ponerlas a la venta. Lo que pretende es liberar a su familia de problemas económicos cuando se produzca el fatal desenlace.";
    public static final String DESCRIPCIO_GOT = "La historia se desarrolla en un mundo ficticio de carácter medieval donde hay Siete Reinos. Hay tres líneas argumentales principales: la crónica de la guerra civil dinástica por el control de Poniente entre varias familias nobles que aspiran al Trono de Hierro, la creciente amenaza de los Otros, seres desconocidos que viven al otro lado de un inmenso muro de hielo que protege el Norte de Poniente, y el viaje de Daenerys Targaryen, la hija exiliada del rey que fue asesinado en una guerra civil anterior, y que pretende regresar a Poniente para reclamar sus derechos. Tras un largo verano de varios años, el temible invierno se acerca a los Siete Reinos. Lord Eddard Stark, señor de Invernalia, deja sus dominios para ir a la corte de su amigo, el rey Robert Baratheon en Desembarco del Rey, la capital de los Siete Reinos. Stark se convierte en la Mano del Rey e intenta desentrañar una maraña de intrigas que pondrá en peligro su vida y la de todos los suyos. Mientras tanto diversas facciones conspiran con un solo objetivo: apoderarse del trono.";
    public static final String DESCRIPCIO_JESSICA = "Jessica Jones nació como un personaje secundario, como una joven normal con un cuelgue por Peter Parker (Spider-Man) y más tarde por Johnny Storm (La Antorcha Humana). Un día volvía a casa en coche con su familia y tuvieron la mala suerte de chocar contra un convoy militar que cargaba productos radioactivos. Su familia murió y ella entró en coma para despertar más tarde con fuerza sobrehumana, invulnerabilidad y capacidad para volar. Desde que su corta vida como superheroína terminó en tragedia, Jessica Jones ha estado reconstruyendo su vida personal y su carrera como detective irascible y sardónica junto a otro ex superhéroe algo turbulento. Plagada de odio y estres postraumático, Jones batalla demonios dentro y fuera del trabajo usando sus habilidades extraordinarias, sobre todo si están dispuestos a extender un cheque.";
    public static final String DESCRIPCIO_SONSOFANARCHY = "Aclamado drama muy a la americana creado por Kurt Sutter (The Shield), que se colocó rápidamente en lo más alto de la cadena FX en lo que a series de ficción se refiere. Narra las aventuras de los Hijos de la Anarquía, una banda de moteros con su propio código de moral a los que no les importa cometer actos criminales y atroces con tal de su subsistencia. La serie se centra en la sede original de los Hijos de la Anarquía, los Redwood Original, fundadores de la banda, con base actual en Charming, California. El protagonista es Jackson Teller (Charlie Hunnam, Queer As Folk, Hooligans), vicepresidente de la banda, hijo de uno de los difuntos fundadores de la banda y adoptado por Clay Morrow (Ron Perlman, Hellboy, Drive), co-fundador de la banda que se casó con la madre de Jax, Gemma Teller (Katey Sagal, No con mis hijas, Perdidos) tras esta quedarse esta viuda. Esta asociación para amantes de las dos ruedas es mucho más que un simple club de moteros. Su actividad delictiva ha ido in crescendo desde su nacimiento y las sedes se han ido extendiendo hasta contar con miembros alrededor de todo el globo. Sin embargo, tras el incendio de uno de sus almacenes, Jax empieza a rechazar la idea de sus actividades criminales, de su pertenencia a la banda, e incluso de su simple existencia.";
    public static final String DESCRIPCIO_THEDEFENDERS = "Daredevil, Jessica Jones, Luke Cage y Iron Fist unen fuerzas para enfrentarse a sus enemigos comunes mientras una siniestra conspiración amenaza Nueva York.";
    public static final String DESCRIPCIO_FTWD = "Fear The Walking Dead, el esperado spin-off de The Walking Dead, es una serie dramática que explora el inicio del apocalipsis desde el punto de vista de una familia desestructurada: Sean Cabrera, profesor divorciado consejero de orientación femenina, y sus dos hijos. De la ciudad nace un brote de algo misterioso que amenaza la estabilidad de Madison Clark y Travis Manawa. La presión de sacar adelante dos familias queda en un segundo plano cuando la sociedad comienza a desmoronarse. Deberán adaptarse y sobrevivir a la vez que aceptan las historias más oscuras";
    public static final String DESCRIPCIO_HOUSEOFCARDS = "El implacable y manipulador congresista Francis Underwood (Kevin Spacey), con la complicidad de su calculadora mujer (Robin Wright), maneja con gran destreza los hilos de poder en Washington. Su intención es ocupar la Secretaría de Estado del nuevo gobierno. Sabe muy bien que los medios de comunicación son vitales para conseguir su propósito, por lo que decide convertirse en la \"garganta profunda\" de la joven y ambiciosa periodista Zoe Barnes (Kate Mara), a la que ofrece exclusivas para desestabilizar y hundir a sus adversarios políticos. Nueva adaptación de la novela homónima de Michael Dobbs, en la que se basó una miniserie británica de 1990.";
    public static final String DESCRIPCIO_SIMPSONS = "Los Simpsons es una comedia americana de animación creada por Matt Groening para la compañía Fox. La serie es una parodia satírica del estilo de la clase media americana encarnada por una familia con ese mismo nombre, compuesta por Homer, Marge, Bart, Lisa, y Maggie Simpson. La serie se ubica en la ciudad ficticia de Springfield y parodia la cultura, la sociedad, la televisión americanos y muchos otros aspectos de la condición humana";
    public static final String DESCRIPCIO_3 = "3% es una serie de suspenso y ciencia ficción brasileña de Netflix. Es un reinicio de una serie web de 2011 del mismo nombre creado por Pedro Aguilera que tuvo su episodio piloto producido y subido a YouTube.1\u200B Constituye el primer proyecto de producción original de Netflix en Brasil, y es una de las primeras series de Netflix producidas en idioma distinto del inglés.2\u200B3\u200B 3% está protagonizada por Bianca Comparato y João Miguel";
    public static final String DESCRIPCIO_LOS100 = "Situada 97 años después de una guerra nuclear que ha destruido la civilización, los supervivientes de una nave espacial, que han sobrevivido durante 3 generaciones en el espacio, envían 100 delincuentes juveniles \"para testear\" las condiciones de la Tierra, con la esperanza de eventualmente volver a poblar el planeta. El grupo de jóvenes tratará de sobrevivir en un entorno desconocido y hostil a pesar de las brechas que se abren entre ellos, unos partidarios de seguir en conexión con la nave, otros a favor de empezar de cero sin depender de nadie. Mientras, en la nave, las luchas por el poder político se recrudecen, llevando a los dirigentes a situaciones extremas y difíciles decisiones";
    public static final String DESCRIPCIO_NARCOS = "Serie que narra los esfuerzos de Estados Unidos, a través principalmente de la DEA y las autoridades y policía de Colombia, para luchar en la década de los 80 contra el narcotraficante Pablo Escobar y el cartel de Medellín, una de las organizaciones criminales más ricas y despiadadas en la historia de la delincuencia moderna.";
    public static final String DESCRIPCIO_CATRASTOFES = "Basada en los bestsellers mundiales del escritor Lemony Snicket (pseudónimo de Daniel Handler) y protagonizada por Neil Patrick Harris, ganador de los premios Emmy y Tony, Una serie de catastróficas desdichas relata la trágica historia de los huérfanos Baudelaire —Violet, Klaus y Sunny—, cuyo malvado tutor, el conde Olaf, no se detendrá ante nada para adueñarse de su herencia. Los hermanos tienen que adelantarse siempre a Olaf, desbaratando todos sus planes y argucias, para descubrir pistas sobre la misteriosa muerte de sus padres.";
    public static final String DESCRIPCIO_AGENTES = "Basada en los bestsellers mundiales del escritor Lemony Snicket (pseudónimo de Daniel Handler) y protagonizada por Neil Patrick Harris, ganador de los premios Emmy y Tony, Una serie de catastróficas desdichas relata la trágica historia de los huérfanos Baudelaire —Violet, Klaus y Sunny—, cuyo malvado tutor, el conde Olaf, no se detendrá ante nada para adueñarse de su herencia. Los hermanos tienen que adelantarse siempre a Olaf, desbaratando todos sus planes y argucias, para descubrir pistas sobre la misteriosa muerte de sus padres.";
    public static final String DESCRIPCIO_FLASH = "Después de que un acelerador de partículas cause una extraña tormenta, al investigador científico de la policía, Barry Allen, le cae un rayo y entra en coma. Meses después despierta con el poder de moverse a súper velocidad permitiéndole ser el ángel de la guardia de Central City. Aunque al principio se siente entusiasmado con sus nuevos poderes, Barry descubre que no es el único “meta-humano” que se originó tras la explosión del acelerador – y no todo el mundo está usando sus nuevos poderes para el bien. Los compañeros del laboratorio STAR dedican su vida a ayudar a Barry a proteger a los inocentes. Por ahora, solo algunos amigos cercanos saben que Barry es, literalmente, el hombre más rápido del mundo, pero no pasará mucho hasta que el mundo conozca que ahora Barry Allen es … Flash.";



}
